Add 'cleanWorkspace' option to clean workspace at beginning of build
The [rails_translation_manager job](https://ci.integration.publishing.service.gov.uk/job/rails_translation_manager/)
passes successfully on new branches, but on every subsequent build
it will fail with a long log of unrelated errors along the lines
of:
> error: wrong index v2 file size in .git/objects/pack/pack-b360de1f7cfbce9b7fa4b4c11ea4dc4daea3d1f7.idx

We've confirmed that manually deleting the workspace for the
master branch for Rails Translation Manager (on a specific ci-agent)
causes the build to clone everything from scratch, so fixes the
issue.

There is a plugin - WS Cleanup - which is installed on all of our
Jenkins environments: https://github.com/alphagov/govuk-puppet/blob/1ee7892b65b2edf91682261186b1b57041e82a8c/hieradata_aws/class/integration/ci_master.yaml#L421-L422
This code change calls the cleanWs() method as per
https://github.com/jenkinsci/ws-cleanup-plugin.

Ideally, we would simply configure workspace deletion in the Jenkins
UI. We can see that for [certain jobs](https://ci.integration.publishing.service.gov.uk/job/Deploy_App_Downstream/configure),
the plugin provides an option to "Delete workspace before build starts".
HOWEVER, there is no such option on the rails_translation_manager job (nor
any job built from the application_build_job.xml.erb template).
We attempted to shoehorn the config option into these jobs in
https://github.com/alphagov/govuk-puppet/pull/11309,
but the changes had no effect, so now we will now offer an option
configurable from the Jenkinsfile.

Trello: https://trello.com/c/Pq7ffzxM/2752-investigate-rails-translation-manager-failing-builds